services:

  postgresql:
    image: postgres:12-alpine
    # No exponemos al host, solo interno
    expose:
      - "6432"
    environment:
      POSTGRES_USER: ${SQL_USER}
      POSTGRES_PASSWORD: ${SQL_PASS}
      POSTGRES_DB: ${SQL_BASE}
    volumes:
      - ./volumes/db:/var/lib/postgresql/data

  hmdm:
    image: headwindmdm/hmdm:0.1.5
    # Solo puertos internos
    expose:
      - "8080"
      - "8443"
      - "31000"
    volumes:
      - ./volumes/work:/usr/local/tomcat/work
      - ./volumes/letsencrypt:/etc/letsencrypt
      - ./volumes/hmdm-config:/usr/local/tomcat/conf/Catalina/localhost
    environment:
      SQL_HOST: postgresql
      SQL_USER: ${SQL_USER}
      SQL_BASE: ${SQL_BASE}
      SQL_PASS: ${SQL_PASS}
      BASE_DOMAIN: ${BASE_DOMAIN}
      LOCAL_IP: ${LOCAL_IP}
      PROTOCOL: ${PROTOCOL}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      SHARED_SECRET: ${SHARED_SECRET}
      HMDM_VARIANT: ${HMDM_VARIANT}
      DOWNLOAD_CREDENTIALS: ${DOWNLOAD_CREDENTIALS}
      HMDM_URL: ${HMDM_URL}
      CLIENT_VERSION: ${CLIENT_VERSION}
      FORCE_RECONFIGURE: ${FORCE_RECONFIGURE}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hmdm.rule=Host(`${BASE_DOMAIN}`)"
      - "traefik.http.routers.hmdm.entrypoints=websecure"
      - "traefik.http.routers.hmdm.tls.certresolver=letsencrypt"
      - "traefik.http.services.hmdm.loadbalancer.server.port=8080"
